const COOKIE="proposal_session";
async function hash(s){const h=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function session(env){const exp=Date.now()+86400000;return exp+"."+await hash(exp+"."+env.SESSION_SECRET)}
async function valid(req,env){const c=req.headers.get("Cookie")||"";const m=c.match(new RegExp(COOKIE+"=([^;]+)"));if(!m)return false;const p=m[1].split(".");if(p.length!==2||Date.now()>Number(p[0]))return false;return p[1]===await hash(p[0]+"."+env.SESSION_SECRET)}
function proposal(){return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Will You Marry Me?</title><link rel="stylesheet" href="/style.css"></head><body><section class="screen"><div class="proposal-card"><div class="sparkles">✦ &nbsp; ✧ &nbsp; ✦</div><div class="message"><p>To the girl I adore most...</p><p>To the girl with whom I feel myself...</p><p>To the girl who captured my heart's feelings and made me unable to withstand them...</p><p>To the girl who means more to me than words could ever explain...</p><p class="special">To you, Saji. ❤️</p></div><div class="divider">♥</div><p class="transition">And after all these feelings, there is only one question left...</p><h2>Will the Beauty<br>marry the Beast?</h2><h3>Will you marry me, Saji?</h3><div class="ring">💍</div><div class="buttons"><button class="yes-button" onclick="yes()">Yes ❤️</button><button class="think-button" onclick="think()">I need to think 😭</button></div><p id="answer"></p></div></section><audio autoplay loop id="m"><source src="/proposal.mp3" type="audio/mpeg"></audio><script>function yes(){answer.textContent="You just made the Beast the happiest person alive. ❤️"}function think(){answer.textContent="Okay... I'll wait. But I'm really hoping for that YES. 🥹❤️"}document.getElementById("m").volume=.45</script></body></html>`}
export default {async fetch(req,env){const u=new URL(req.url);
if(u.pathname==="/unlock"&&req.method==="POST"){let x={};try{x=await req.json()}catch{}if(String(x.password||"")!==env.PROPOSAL_PASSWORD)return new Response("Unauthorized",{status:401});const t=await session(env);return new Response("OK",{headers:{"Set-Cookie":`${COOKIE}=${t}; Max-Age=86400; Path=/; HttpOnly; Secure; SameSite=Strict`,"Cache-Control":"no-store"}})}
if(u.pathname==="/proposal"){if(!await valid(req,env))return Response.redirect(new URL("/",req.url),302);return new Response(proposal(),{headers:{"Content-Type":"text/html;charset=UTF-8","Cache-Control":"no-store"}})}
if(u.pathname==="/proposal.mp3"&&!await valid(req,env))return new Response("Unauthorized",{status:401});
return env.ASSETS.fetch(req)}};